"""Add Date modified to NovelChapters

Revision ID: 107c8fa32d58
Revises: 045ea204aa1b
Create Date: 2024-12-19 22:35:20.769608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = '107c8fa32d58'
down_revision = '045ea204aa1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novelchapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_edited', sa.DateTime(), nullable=True))

    
    # Set the current timestamp for all existing rows
    novelchapter = sa.table(
        'novelchapter',
        sa.column('date_edited', sa.DateTime())
    )
    op.execute(
        novelchapter.update().values(date_edited=func.now())
    )

    with op.batch_alter_table('novelchapter', schema=None) as batch_op:
        batch_op.alter_column('date_edited', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novelchapter', schema=None) as batch_op:
        batch_op.drop_column('date_edited')

    # ### end Alembic commands ###
