"""Increased Limit on String

Revision ID: 831a9ba297d5
Revises: 107c8fa32d58
Create Date: 2024-12-23 19:57:45.339958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831a9ba297d5'
down_revision = '107c8fa32d58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novel', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('chinese_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=100000),
               existing_nullable=True)

    with op.batch_alter_table('novelchapter', schema=None) as batch_op:
        batch_op.alter_column('chapter_title',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novelchapter', schema=None) as batch_op:
        batch_op.alter_column('chapter_title',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('novel', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=100000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('chinese_name',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
